# ARM Linux 交叉编译工具链
# 目标: arm-linux-gnueabihf (ARMv7-A 硬浮点)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
find_program(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
find_program(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
find_program(CMAKE_SIZE arm-linux-gnueabihf-size)
if(NOT CMAKE_C_COMPILER)
  message(FATAL_ERROR "未找到 arm-linux-gnueabihf-gcc，请安装: sudo apt install gcc-arm-linux-gnueabihf")
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
